config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'endpoints#index'
  resources :endpoints do
    get 'stats', to: 'stats#show'
  end

  get 'stats', to: 'stats#index'

  namespace :api do
    get '/*path', to: 'endpoints#execute', constraints: EndpointConstraint
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endpoint.rb
# frozen_string_literal: true

class Endpoint < ApplicationRecord
  has_many :logs, class_name: 'EndpointLog'

  validates :slug, uniqueness: true, presence: true
  validates :sql_statement, presence: true
  validates_with SqlValidator
end

app/models/endpoint_log.rb
# frozen_string_literal: true

class EndpointLog < ApplicationRecord
  belongs_to :endpoint

  scope :today, -> { where('DATE(created_at) = ?', Date.today) }
  scope :in_hours, -> (hours) { where('created_at > ? ', DateTime.now - hours.hours) }
end

app/controllers/api/endpoints_controller.rb
module Api
  class EndpointsController < ApiController
    before_action :set_endpoint

    def execute
      render json: EndpointExecutorService.run(@endpoint)
    end

    private

    def set_endpoint
      @endpoint = Endpoint.find_by_slug(params[:path])
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/endpoints_controller.rb
# frozen_string_literal: true

class EndpointsController < ApplicationController
  before_action :set_endpoint, only: %i[show edit update destroy]

  # GET /endpoints
  # GET /endpoints.json
  def index
    @endpoints = Endpoint.all
  end

  # GET /endpoints/1
  # GET /endpoints/1.json
  def show; end

  # GET /endpoints/new
  def new
    @endpoint = Endpoint.new
  end

  # GET /endpoints/1/edit
  def edit; end

  # POST /endpoints
  # POST /endpoints.json
  def create
    @endpoint = Endpoint.new(endpoint_params)

    respond_to do |format|
      if @endpoint.save
        format.html { redirect_to @endpoint, notice: 'Endpoint was successfully created.' }
        format.json { render :show, status: :created, location: @endpoint }
      else
        format.html { render :new }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endpoints/1
  # PATCH/PUT /endpoints/1.json
  def update
    respond_to do |format|
      if @endpoint.update(endpoint_params)
        format.html { redirect_to @endpoint, notice: 'Endpoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @endpoint }
      else
        format.html { render :edit }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endpoints/1
  # DELETE /endpoints/1.json
  def destroy
    @endpoint.destroy
    respond_to do |format|
      format.html { redirect_to endpoints_url, notice: 'Endpoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_endpoint
    @endpoint = Endpoint.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def endpoint_params
    params.require(:endpoint).permit :slug, :sql_statement
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_endpoint, only: :show

  def show; end

  def index
    @endpoints = Endpoint.all
  end

  private

  def set_endpoint
    @endpoint = Endpoint.find(params[:endpoint_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/endpoints_helper.rb
# frozen_string_literal: true

module EndpointsHelper
end

app/views/endpoints/_form.html.erb
<%= form_for @endpoint do |f| %>
  <% if endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
      <% endpoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>
  <div>
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>
  <div>
    <%= f.label :sql_statement %>
    <%= f.text_area :sql_statement %>
  </div>
  <div class="acttitleions">
    <%= f.submit %>
  </div>
<% end %>

app/views/endpoints/edit.html.erb
<h1>Editing Endpoint</h1>

<%= render 'form', endpoint: @endpoint %>

<%= link_to 'Show', @endpoint %> |
<%= link_to 'Back', endpoints_path %>

app/views/endpoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Endpoints</h1>

<table>
  <thead>
    <tr>
      <th>Slug</th>
      <th>SQL statement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @endpoints.each do |endpoint| %>
      <tr>
        <td><%= endpoint.slug %></td>
        <td><%= endpoint.sql_statement%></td>

        <td><%= link_to  'Stats', endpoint_stats_path(endpoint) %></td>
        <td><%= link_to 'Edit', edit_endpoint_path(endpoint) %></td>
        <td><%= link_to 'Destroy', endpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endpoint', new_endpoint_path %>
<%= link_to 'Total Stats', stats_path %>

app/views/endpoints/new.html.erb
<h1>New Endpoint</h1>

<%= render 'form', endpoint: @endpoint %>

<%= link_to 'Back', endpoints_path %>

app/views/endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_endpoint_path(@endpoint) %> |
<%= link_to 'Back', endpoints_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SqlEndpoints</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stats/index.html.erb
<h1>Endpoint Hit Stats:</h1>

<table>
  <thead>
    <tr>
      <th>Endpoint Slug</th>
      <th>Today</th>
      <th>6 hours</th>
      <th>12 hours</th>
      <th>24 hours</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @endpoints.each do |endpoint| %>
    <tr>
      <td><%= endpoint.slug %></td>
      <td><%= endpoint.logs.today.count %></td>
      <td><%= endpoint.logs.in_hours(6).count %></td>
      <td><%= endpoint.logs.in_hours(12).count %></td>
      <td><%= endpoint.logs.in_hours(24).count %></td>
      <td><%= endpoint.logs.count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stats/show.html.erb
<h1>Endpoints Hits Statistics:</h1>

Endpoint Slug: <%= @endpoint.slug %>

<table>
  <tr>
    <td>Today hits</td>
    <td><%= @endpoint.logs.today.count %></td>
  </tr>
  <tr>
    <td>Last 6 hours hits</td>
    <td><%= @endpoint.logs.in_hours(6).count %></td>
  </tr><tr>
  <td>Last 12 hours hits</td>
  <td><%= @endpoint.logs.in_hours(12).count %></td>
</tr><tr>
  <td>Last 24 hours hits</td>
  <td><%= @endpoint.logs.in_hours(24).count %></td>
</tr>
  <tr>
    <td>Total</td>
    <td><%= @endpoint.logs.count %></td>
  </tr>
</table>